version: '3.9'

services:
  mysql:
    image: mysql:8
    volumes:
      -db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rocketseat-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    container_name: mysql
    networks:
      - primeira-network

  api-rocketseat:
    container_name: api-rocket
    build: 
      context: .
    ports:
      - 3001:3000
    depends_on:
      - mysql
    networks:
      - primeira-network

networks:
  primeira-network:
    driver: bridge

volumes:
  db: 